feat: add basic folder structure
Virturon/rms-be-api pull request #1
Opened 2024-04-02 11:57 UTC by anujakiran

PR #1
Initial setup and basic code structure

2024-04-02 15:09 UTC, Kiransukumaran requested changes
Please add the following as well
1) Update the readme file with local setup information and details

2024-04-02 15:09 UTC, Kiransukumaran commented on .eslintrc.json
> +    "es2021": true,
Add remaining config from wl-conversation

2024-04-02 15:09 UTC, Kiransukumaran commented on .gitignore
> +build
Why this changes were removed ?

2024-04-02 15:09 UTC, Kiransukumaran commented on package.json
> +    "dotenv": "^16.4.5",
Remove dotenv as it is not needed in 20.xx

2024-04-02 15:09 UTC, Kiransukumaran commented on package.json
> +    "ts-node": "^10.9.2"
dev dependency

2024-04-02 15:09 UTC, Kiransukumaran commented on src/app.ts
> +const app = express();
add new line after line 2

2024-04-02 15:09 UTC, Kiransukumaran commented on src/app.ts
> +app.get('/', (_req: Request, res: Response) => {
Remove this endpoint

2024-04-02 15:09 UTC, Kiransukumaran commented on src/app.ts
> +app.use(router);
Add required middlewares for security and cors

2024-04-02 15:09 UTC, Kiransukumaran commented on src/controller/statusController.ts
> +  const response = { Environment: process.env.NODE_ENV, version: version };
Add Application name
Environment => environment

2024-04-02 15:09 UTC, Kiransukumaran commented on src/controller/statusController.ts
> +const getStatus = (_req: Request, res: Response) => {
export const getStatus

2024-04-02 15:09 UTC, Kiransukumaran commented on src/helper/responseHelper.ts
> +  res.status(200).json({
Allow other success status codes as well like 201 created

2024-04-02 15:09 UTC, Kiransukumaran commented on src/helper/responseHelper.ts
> +const responseHelperSuccess = (res: Response, result: object) => {
export const

2024-04-02 15:09 UTC, Kiransukumaran commented on tsconfig.json
> +    "target": "es2016",
refer to wl-conversation

2024-04-02 15:09 UTC, Kiransukumaran commented on tsconfig.json
> +  "include": ["src/**/*.ts", "src/*.ts"],
?????

2024-04-02 15:09 UTC, Kiransukumaran commented on src/helper/responseHelper.ts
> +const responseHelperSuccess = (res: Response, result: object) => {
use more sensible type

2024-04-02 15:09 UTC, Kiransukumaran commented on src/helper/responseHelper.ts
> +    status: 'OK',
lowercase

2024-04-02 16:36 UTC, anujakiran commented on .gitignore
> +build
I thought it was unintentional. Please confirm if it needs to be added back

2024-04-02 17:09 UTC, anujakiran commented on src/helper/responseHelper.ts
> +    status: 'OK',
done

2024-04-02 17:09 UTC, anujakiran commented on src/helper/responseHelper.ts
> +const responseHelperSuccess = (res: Response, result: object) => {
done

2024-04-02 17:09 UTC, anujakiran commented on tsconfig.json
> +  "include": ["src/**/*.ts", "src/*.ts"],
done

2024-04-02 17:10 UTC, anujakiran commented on tsconfig.json
> +    "target": "es2016",
ok

2024-04-02 17:10 UTC, anujakiran commented on src/helper/responseHelper.ts
> +const responseHelperSuccess = (res: Response, result: object) => {
changed

2024-04-02 17:17 UTC, anujakiran commented on package.json
> +    "dotenv": "^16.4.5",
not possible

2024-04-04 15:47 UTC, Kiransukumaran commented on .gitignore
> +build
for now lets keep it like this

2024-04-04 15:49 UTC, Kiransukumaran approved these changes

2024-04-04 16:07 UTC, merged