feat: db structure and migrations
Virturon/rms-be-api pull request #7
Opened 2024-04-15 17:53 UTC by anujakiran

DB structures and migrations

2024-04-16 02:25 UTC, Kiransukumaran requested changes
Can ignore some comments in migration

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/migrations/20240415170019-user.ts
> +      createdAt: { type: DataTypes.DATE, defaultValue: new Date() },
You might get a problem here on the dates part later

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/migrations/20240415170019-user.ts
> +  async down(queryInterface: QueryInterface) {
Missing foreign key attribute relation here

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/migrations/20240415170542-role.ts
> +        type: DataTypes.BIGINT,
This will be an array of bigints as we need to add multiple scopes to a role

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/migrations/20240415170951-addresses.ts
> +        type: DataTypes.STRING,
Do we need to collect address like this.

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/models/scope.ts
> +    scopes: {
Only one scope per entry

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/models/user.ts
> +    phoneNumber: DataTypes.STRING,
As we have phone login as well better make this unique as well

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/seeders/20240415171636-user.ts
> +        updatedAt: new Date(),
No need to send user table with dummy values maybe set something like an admin account

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/seeders/20240415172252-role.ts
> +        createdAt: new Date(),
Do we need this created and updated fields in seed

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/seeders/20240415173007-address.ts
> +        id: 2,
This as well no need to seed

2024-04-16 02:25 UTC, Kiransukumaran commented on src/db/sequelize/index.ts
> +  development: {
Rename file path to db/config/index.ts

2024-04-21 07:33 UTC, Kiransukumaran commented on src/db/models/role.ts
> +    tableName: 'roles',
Nit But can you add timestamps true next time in all the models

2024-04-21 07:34 UTC, Kiransukumaran commented on src/db/seeders/20240421072440-user.ts
> +        email: 'John@gmail.com',
This seed is not required

2024-04-21 07:34 UTC, Kiransukumaran requested changes
Please remove the seed file for user

2024-04-21 07:36 UTC, anujakiran commented on src/db/seeders/20240421072440-user.ts
> +        email: 'John@gmail.com',
Can you please explain the reason?

2024-04-21 07:51 UTC, anujakiran commented on src/db/seeders/20240421072440-user.ts
> +        email: 'John@gmail.com',
done

2024-04-22 13:32 UTC, Kiransukumaran approved these changes

2024-04-22 13:34 UTC, merged